# Generated by Django 5.0.7 on 2024-07-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('street_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Edzőtermek címe',
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('price_group', models.CharField(max_length=25)),
                ('comment', models.CharField(max_length=500)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweatCircus.gymaddress')),
            ],
            options={
                'verbose_name_plural': 'Edzőtermek',
            },
        ),
    ]
