# Generated by Django 5.1 on 2024-08-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='address',
        ),
        migrations.AddField(
            model_name='gymaddress',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweatCircus.gymaddress'),
        ),
    ]
