# Generated by Django 5.1 on 2024-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0002_remove_gym_address_gymaddress_name_alter_gym_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymaddress',
            name='street_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
