# Generated by Django 5.1 on 2024-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0003_alter_gymaddress_street_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymaddress',
            name='street_number',
            field=models.CharField(max_length=50),
        ),
    ]
