# Generated by Django 5.1 on 2024-08-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0005_remove_gymaddress_name_gym_address_alter_gym_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='address',
        ),
        migrations.AddField(
            model_name='gymaddress',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweatCircus.gymaddress'),
        ),
    ]
