# Generated by Django 5.1 on 2024-08-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0007_remove_gymaddress_name_gym_address_alter_gym_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Városok',
            },
        ),
        migrations.AlterField(
            model_name='gymaddress',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SweatCircus.city'),
        ),
    ]
