# Generated by Django 5.1 on 2024-08-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0008_city_alter_gymaddress_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
    ]
