# Generated by Django 5.1 on 2024-08-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0009_rename_name_city_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
    ]
