# Generated by Django 5.1 on 2024-08-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0010_rename_city_name_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymaddress',
            old_name='city',
            new_name='city_name',
        ),
    ]
