# Generated by Django 5.1 on 2024-08-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0011_rename_city_gymaddress_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='comment',
        ),
    ]
