# Generated by Django 5.1 on 2024-08-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0012_remove_gym_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('body_goals', models.CharField(max_length=250)),
                ('comment', models.CharField(default='-', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Regisztrált felhasználók',
            },
        ),
    ]
