# Generated by Django 5.1 on 2024-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0014_bodygoals_alter_gym_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(default='kg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default='cm'),
        ),
    ]
