# Generated by Django 5.1 on 2024-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0015_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
