# Generated by Django 5.1 on 2024-08-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0016_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
    ]
