# Generated by Django 5.1 on 2024-09-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0018_exercises_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodyGoals',
        ),
    ]
