# Generated by Django 5.1 on 2024-09-07 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0021_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=250)),
                ('reps', models.CharField(max_length=250)),
                ('comment', models.TextField(default='')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweatCircus.days')),
                ('exerciseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweatCircus.exercises')),
                ('muscleGroupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweatCircus.musclegroup')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Edzés tervek',
            },
        ),
    ]
