# Generated by Django 5.1 on 2024-09-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0022_workoutplans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuscleGroup',
            new_name='MuscleGroups',
        ),
    ]
