# Generated by Django 5.1 on 2024-12-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0024_isrestday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isrestday',
            old_name='bool',
            new_name='is_rest_day',
        ),
    ]
