# Generated by Django 5.1 on 2024-12-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweatCircus', '0025_rename_bool_isrestday_is_rest_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isrestday',
            name='is_rest_day',
        ),
    ]
